[tool.poetry]
name = "capirci"
version = "0.1.0"
description = "Chat And Program Industrial Robots through Convenient Interaction"
authors = ["Luigi Gargioni <luigi.gargioni@gmail.com>"]

[tool.poetry.scripts]
start = "python manage.py runserver"

[tool.poetry.dependencies]
Django = "^4.0.5"
django-mysql = "^4.7.0"
nltk = "^3.7"
numpy = "^1.23.0"
opencv-python = "^4.6.0.66"
Pillow = "^9.1.1"
python = "^3.10"
pythonping = "^1.1.1"
pytz = "^2022.1"
pywin32 = "^304"
stanza = "^1.4.0"
word2number = "^1.1"

[tool.poetry.dev-dependencies]
black = "22.3.0"
flake8 = "^4.0.1"
poetryup = "^0.8.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
