[tool.poetry]
name = "capirci"
version = "0.1.0"
description = "Chat And Program Industrial Robots through Convenient Interaction"
authors = ["Luigi Gargioni <luigi.gargioni@gmail.com>"]

[tool.poetry.scripts]
start = "python manage.py runserver"

[tool.poetry.dependencies]
black = "22.3.0"
certifi = "^2022.5.18.1"
chardet = "^4.0.0"
Django = "^4.0.5"
django-mysql = "^4.7.0"
idna = "^3.3"
mysqlclient = "^2.1.0"
nltk = "^3.7"
numpy = "^1.22.4"
opencv-python = "^4.5.5.64"
Pillow = "^9.1.1"
psutil = "^5.9.1"
python = "^3.10"
pythonping = "^1.1.1"
pytz = "^2022.1"
pywin32 = "^304"
requests = "^2.27.1"
setuptools = "^62.3.2"
six = "^1.16.0"
sqlparse = "^0.4.2"
stanfordcorenlp = "^3.9.1.1"
stanza = "^1.4.0"
urllib3 = "^1.26.9"
word2number = "^1.1"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
