# Generated by Django 4.2.2 on 2023-06-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_alter_task_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="object",
            name="contour",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="object",
            name="photo",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="object",
            name="shape",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
