# Generated by Django 4.2.2 on 2023-06-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_object_contour_object_photo_object_shape"),
    ]

    operations = [
        migrations.RenameField(
            model_name="action",
            old_name="point",
            new_name="positions",
        ),
    ]
