# Generated by Django 4.0.5 on 2022-06-22 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('model', models.CharField(choices=[('C', 'Cobotta'), ('V', 'VS-060')], max_length=1)),
                ('port', models.IntegerField(default=0)),
                ('cameraip', models.GenericIPAddressField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Robots',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(default=None, max_length=200)),
                ('description', models.CharField(default=None, max_length=200)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('shared', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='UserRobot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.robot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserRobots',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('keywords', django_mysql.models.ListCharField(models.CharField(max_length=50), default=None, max_length=1019, size=20)),
                ('shared', models.BooleanField(default=False)),
                ('force', models.IntegerField(default=2)),
                ('height', models.FloatField(default=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Objects',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('shared', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('robot', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.userrobot')),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('point', models.CharField(max_length=10000)),
                ('shared', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('robot', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.userrobot')),
            ],
            options={
                'verbose_name_plural': 'Actions',
            },
        ),
    ]
